---
driver:
  name: ec2
  region: eu-west-1
  require_chef_omnibus: true
  instance_type: t2.micro
  subnet_id: subnet-0e9b6138ff1ce18f2
  associate_public_ip: true
  aws_ssh_key_id: DevOpsStudents

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

# transport:
#   ssh_key: ~/.ssh/DevOpsStudents.pem

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[uber_nginx_cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
